<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="SeniorProject_1.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>This is the Admin Page...!</h1>
    <hr />
    <asp:DropDownList ID="DDL1" runat="server">
        <asp:ListItem>CourseTable</asp:ListItem>
        <asp:ListItem>student1</asp:ListItem>
        <asp:ListItem>Tutor</asp:ListItem>
    </asp:DropDownList>
    
    <asp:Button ID="Butsubmit" runat="server" Text="Submit" OnClick="Butsubmit_Click" />
    <asp:GridView ID="GdCourse" runat="server" DataKeyNames="Cid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdCourse_RowCancelingEdit" OnRowDeleting="GdCourse_RowDeleting" OnRowEditing="GdCourse_RowEditing" OnRowUpdating="GdCourse_RowUpdating"></asp:GridView>
    <asp:GridView ID="GdStudent" runat="server" DataKeyNames="Stid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdStudent_RowCancelingEdit" OnRowDeleting="GdStudent_RowDeleting" OnRowEditing="GdStudent_RowEditing" OnRowUpdating="GdStudent_RowUpdating"></asp:GridView>
    <asp:GridView ID="GdTutor" runat="server" DataKeyNames="id" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdTutor_RowCancelingEdit" OnRowDeleting="GdTutor_RowDeleting" OnRowEditing="GdTutor_RowEditing" OnRowUpdating="GdTutor_RowUpdating"></asp:GridView>
</asp:Content>
